use std::collections::HashMap;
use std::net::{SocketAddr, UdpSocket};
use std::num::NonZeroU32;
use std::sync::{Arc, Mutex};
use std::time::{Duration, Instant};

use str0m::change::{SdpAnswer, SdpOffer, SdpPendingOffer};
use str0m::format::Codec;
use str0m::media::{Direction, MediaKind, MediaTime, Mid};
use str0m::net::{Protocol, Receive};
use str0m::channel::{ChannelConfig, Reliability};
use str0m::{Candidate, Event, IceConnectionState, Input, Output, Rtc, RtcConfig};

use elementium_types::{
    IceConnectionState as IceState, PeerConnectionState, SdpType, SessionDescription,
};

/// Events emitted by a peer connection to the application layer.
#[derive(Debug, Clone)]
pub enum PcEvent {
    /// ICE connection state changed.
    IceConnectionStateChange(IceState),
    /// Peer connection state changed.
    ConnectionStateChange(PeerConnectionState),
    /// A local ICE candidate was gathered.
    IceCandidate(String),
    /// ICE gathering completed (null candidate).
    IceGatheringComplete,
    /// DTLS+ICE connected, media can flow.
    Connected,
    /// A new remote media track was added.
    RemoteTrackAdded { mid: String, kind: String },
    /// Received audio data (Opus packet).
    AudioData(Vec<u8>),
    /// Received video data (VP8 packet).
    VideoData(Vec<u8>),
}

/// Shared state for a single peer connection.
pub struct PeerConnectionInner {
    pub id: String,
    pub rtc: Rtc,
    pub audio_mid: Option<Mid>,
    pub video_mid: Option<Mid>,
    pub pending_offer: Option<SdpPendingOffer>,
    pub remote_mids: HashMap<Mid, MediaKind>,
    pub audio_frame_count: u64,
    pub video_frame_count: u64,
    pub alive: bool,
    /// Set to true after SDP negotiation triggers DTLS initialization inside str0m.
    /// Before this, calling poll_output would panic in dimpl because handle_timeout
    /// has not been propagated to the DTLS layer (str0m bug: do_handle_timeout
    /// doesn't call dtls.handle_timeout, only init_dtls does).
    pub dtls_initialized: bool,
    /// Cached answer SDP generated by set_remote_description(Offer).
    /// str0m generates the answer during accept_offer, but the WebRTC API expects
    /// createAnswer() to return it separately. Cache it here for that call.
    pub cached_answer: Option<SessionDescription>,
    /// Counter for UDP transmit logging (throttle after first 10).
    pub transmit_log_count: u64,
    /// Counter for UDP receive logging (throttle after first 10).
    pub recv_log_count: u64,
    /// Cached remote ICE candidate SDP strings, re-added after SDP renegotiation.
    /// str0m's accept_offer may clear remote candidates, so we re-add them.
    pub remote_candidates: Vec<String>,
}

/// Thread-safe handle to a peer connection.
pub type PeerConnectionHandle = Arc<Mutex<PeerConnectionInner>>;

/// Create a new peer connection configured for audio and video.
pub fn create_peer_connection(id: String) -> PeerConnectionInner {
    let now = Instant::now();
    let mut rtc = RtcConfig::new()
        .clear_codecs()
        .enable_opus(true)
        .enable_vp8(true)
        .build(now);

    // str0m's DTLS layer (dimpl) requires handle_timeout before any poll_output.
    // Set it immediately so no code path can hit poll_output with last_now=None.
    let _ = rtc.handle_input(Input::Timeout(now));

    PeerConnectionInner {
        id,
        rtc,
        audio_mid: None,
        video_mid: None,
        pending_offer: None,
        remote_mids: HashMap::new(),
        audio_frame_count: 0,
        video_frame_count: 0,
        alive: true,
        dtls_initialized: false,
        cached_answer: None,
        transmit_log_count: 0,
        recv_log_count: 0,
        remote_candidates: Vec::new(),
    }
}

/// Add a local UDP candidate to the peer connection.
pub fn add_local_candidate(pc: &mut PeerConnectionInner, addr: SocketAddr) {
    // 0.0.0.0 is not a valid ICE candidate — resolve to actual interface IP
    let addr = if addr.ip().is_unspecified() {
        let real_ip = get_local_ip().unwrap_or(std::net::IpAddr::V4(std::net::Ipv4Addr::LOCALHOST));
        SocketAddr::new(real_ip, addr.port())
    } else {
        addr
    };

    match Candidate::host(addr, "udp") {
        Ok(candidate) => {
            tracing::info!(pc_id = %pc.id, %addr, "Adding local ICE candidate");
            pc.rtc.add_local_candidate(candidate);
        }
        Err(e) => {
            tracing::error!(pc_id = %pc.id, %addr, err = %e, "Failed to create local candidate");
        }
    }
}

/// Add a server-reflexive (STUN-discovered public) candidate to the peer connection.
pub fn add_srflx_candidate(
    pc: &mut PeerConnectionInner,
    srflx_addr: SocketAddr,
    base_addr: SocketAddr,
) {
    match Candidate::server_reflexive(srflx_addr, base_addr, "udp") {
        Ok(candidate) => {
            tracing::info!(
                pc_id = %pc.id,
                srflx = %srflx_addr,
                base = %base_addr,
                "Adding srflx ICE candidate"
            );
            pc.rtc.add_local_candidate(candidate);
        }
        Err(e) => {
            tracing::error!(
                pc_id = %pc.id,
                srflx = %srflx_addr,
                base = %base_addr,
                err = %e,
                "Failed to create srflx candidate"
            );
        }
    }
}

/// Discover the local IP address by connecting a UDP socket to a public address.
pub fn get_local_ip() -> Option<std::net::IpAddr> {
    let socket = std::net::UdpSocket::bind("0.0.0.0:0").ok()?;
    // Connect to a public IP (doesn't actually send anything)
    socket.connect("8.8.8.8:80").ok()?;
    socket.local_addr().ok().map(|a| a.ip())
}

/// Info about a data channel to include in the SDP offer.
#[derive(Debug, Clone)]
pub struct DataChannelInfo {
    pub label: String,
    pub ordered: bool,
    pub max_retransmits: Option<u16>,
    pub max_packet_life_time: Option<u16>,
    pub protocol: String,
}

/// Info about a transceiver to include in the SDP offer.
#[derive(Debug, Clone)]
pub struct TransceiverInfo {
    pub kind: MediaKind,
    pub direction: Direction,
}

impl TransceiverInfo {
    /// Create from JS string values.
    pub fn from_js(kind: &str, direction: Option<&str>) -> Self {
        let kind = match kind {
            "video" => MediaKind::Video,
            _ => MediaKind::Audio,
        };
        let direction = match direction {
            Some("sendonly") => Direction::SendOnly,
            Some("recvonly") => Direction::RecvOnly,
            Some("inactive") => Direction::Inactive,
            _ => Direction::SendRecv,
        };
        Self { kind, direction }
    }
}

/// Create an SDP offer with the specified data channels and transceivers.
///
/// Unlike the WebRTC browser API which implicitly includes all added transceivers
/// and data channels, this function takes explicit parameters because str0m's
/// SDP API builds the offer incrementally.
pub fn create_offer(
    pc: &mut PeerConnectionInner,
    data_channels: &[DataChannelInfo],
    transceivers: &[TransceiverInfo],
) -> Result<SessionDescription, String> {
    let mut api = pc.rtc.sdp_api();

    // Add data channels (m=application)
    for dc in data_channels {
        let reliability = if let Some(r) = dc.max_retransmits {
            Reliability::MaxRetransmits { retransmits: r }
        } else if let Some(lt) = dc.max_packet_life_time {
            Reliability::MaxPacketLifetime { lifetime: lt }
        } else {
            Reliability::Reliable
        };
        let config = ChannelConfig {
            label: dc.label.clone(),
            ordered: dc.ordered,
            reliability,
            negotiated: None,
            protocol: dc.protocol.clone(),
        };
        api.add_channel_with_config(config);
    }

    // Add media transceivers (m=audio, m=video)
    for tc in transceivers {
        let mid = api.add_media(tc.kind, tc.direction, None, None, None);
        match tc.kind {
            MediaKind::Audio => pc.audio_mid = Some(mid),
            MediaKind::Video => pc.video_mid = Some(mid),
        }
    }

    let (offer, pending) = api.apply().ok_or("No changes to apply")?;
    pc.pending_offer = Some(pending);
    // NOTE: apply() does NOT call init_dtls — only accept_offer/accept_answer do.
    // dtls_initialized stays false until we receive the remote answer.

    let sdp = offer.to_sdp_string();
    tracing::info!(pc_id = %pc.id, sdp_len = sdp.len(), num_dc = data_channels.len(), num_tc = transceivers.len(), "Created SDP offer");

    Ok(SessionDescription {
        sdp_type: SdpType::Offer,
        sdp,
    })
}

/// Create an SDP answer (after receiving a remote offer).
/// Returns the answer that was generated during set_remote_description(Offer).
pub fn create_answer(pc: &mut PeerConnectionInner) -> Result<SessionDescription, String> {
    pc.cached_answer
        .take()
        .ok_or_else(|| "No cached answer — call set_remote_description(offer) first".into())
}

/// Set the remote description (offer or answer).
pub fn set_remote_description(
    pc: &mut PeerConnectionInner,
    desc: &SessionDescription,
) -> Result<Option<SessionDescription>, String> {
    match desc.sdp_type {
        SdpType::Offer => {
            // Log the setup direction from the remote offer
            if let Some(line) = desc.sdp.lines().find(|l| l.starts_with("a=setup:")) {
                tracing::info!(pc_id = %pc.id, setup = line, "Remote offer DTLS setup direction");
            }
            let offer = SdpOffer::from_sdp_string(&desc.sdp)
                .map_err(|e| format!("Invalid offer SDP: {e}"))?;
            let answer = pc
                .rtc
                .sdp_api()
                .accept_offer(offer)
                .map_err(|e| format!("Failed to accept offer: {e}"))?;
            // accept_offer triggers init_dtls inside str0m
            pc.dtls_initialized = true;
            tracing::info!(pc_id = %pc.id, "accept_offer completed, dtls_initialized=true");

            // Re-add cached remote ICE candidates after accept_offer.
            // str0m's accept_offer may clear remote candidates during renegotiation,
            // but livekit-client won't re-send them (deduplication).
            if !pc.remote_candidates.is_empty() {
                tracing::info!(
                    pc_id = %pc.id,
                    count = pc.remote_candidates.len(),
                    "Re-adding cached remote ICE candidates after renegotiation"
                );
                for cand_sdp in pc.remote_candidates.clone() {
                    match Candidate::from_sdp_string(&cand_sdp) {
                        Ok(candidate) => {
                            pc.rtc.add_remote_candidate(candidate);
                        }
                        Err(e) => {
                            tracing::warn!(pc_id = %pc.id, err = %e, "Failed to re-add cached candidate");
                        }
                    }
                }
            }

            let answer_sdp = answer.to_sdp_string();
            let answer_desc = SessionDescription {
                sdp_type: SdpType::Answer,
                sdp: answer_sdp,
            };
            // Cache for createAnswer() — standard WebRTC API calls createAnswer()
            // after setRemoteDescription(offer), but str0m generates it during accept_offer.
            pc.cached_answer = Some(answer_desc.clone());
            Ok(Some(answer_desc))
        }
        SdpType::Answer => {
            // Log the setup direction from the remote answer — determines DTLS initiator
            if let Some(line) = desc.sdp.lines().find(|l| l.starts_with("a=setup:")) {
                tracing::info!(pc_id = %pc.id, setup = line, "Remote answer DTLS setup direction");
            }
            let answer = SdpAnswer::from_sdp_string(&desc.sdp)
                .map_err(|e| format!("Invalid answer SDP: {e}"))?;
            let pending = pc
                .pending_offer
                .take()
                .ok_or("No pending offer to match answer")?;
            pc.rtc
                .sdp_api()
                .accept_answer(pending, answer)
                .map_err(|e| format!("Failed to accept answer: {e}"))?;
            // accept_answer triggers init_dtls inside str0m
            pc.dtls_initialized = true;
            tracing::info!(pc_id = %pc.id, "accept_answer completed, dtls_initialized=true");
            Ok(None)
        }
    }
}

/// Add a remote ICE candidate.
pub fn add_ice_candidate(
    pc: &mut PeerConnectionInner,
    candidate_sdp: &str,
) -> Result<(), String> {
    if candidate_sdp.is_empty() {
        return Ok(());
    }
    tracing::info!(pc_id = %pc.id, candidate = %candidate_sdp, "Adding remote ICE candidate");
    let candidate = Candidate::from_sdp_string(candidate_sdp)
        .map_err(|e| format!("Invalid ICE candidate: {e}"))?;
    tracing::info!(pc_id = %pc.id, ?candidate, "Parsed remote ICE candidate");
    pc.rtc.add_remote_candidate(candidate);
    // Cache for re-adding after SDP renegotiation (accept_offer may clear candidates)
    if !pc.remote_candidates.contains(&candidate_sdp.to_string()) {
        pc.remote_candidates.push(candidate_sdp.to_string());
    }
    Ok(())
}

/// Write an Opus-encoded audio frame to the peer connection.
pub fn write_audio(pc: &mut PeerConnectionInner, opus_data: &[u8]) -> Result<(), String> {
    let mid = pc.audio_mid.ok_or("No audio mid configured")?;

    let Some(writer) = pc.rtc.writer(mid) else {
        return Err("No writer for audio mid".into());
    };

    let pt = writer
        .payload_params()
        .find(|p| p.spec().codec == Codec::Opus)
        .map(|p| p.pt())
        .ok_or("No Opus payload type negotiated")?;

    // Opus at 48kHz: each 20ms frame = 960 samples
    let samples_per_frame: u64 = 960;
    let rtp_time = MediaTime::new(
        pc.audio_frame_count * samples_per_frame,
        NonZeroU32::new(48_000).unwrap().into(),
    );

    writer
        .write(pt, Instant::now(), rtp_time, opus_data)
        .map_err(|e| format!("Failed to write audio: {e}"))?;

    pc.audio_frame_count += 1;
    Ok(())
}

/// Write a VP8-encoded video frame to the peer connection.
pub fn write_video(pc: &mut PeerConnectionInner, vp8_data: &[u8]) -> Result<(), String> {
    let mid = pc.video_mid.ok_or("No video mid configured")?;

    let Some(writer) = pc.rtc.writer(mid) else {
        return Err("No writer for video mid".into());
    };

    let pt = writer
        .payload_params()
        .find(|p| p.spec().codec == Codec::Vp8)
        .map(|p| p.pt())
        .ok_or("No VP8 payload type negotiated")?;

    // VP8 at 90kHz clock, 30fps = 3000 ticks per frame
    let ticks_per_frame: u64 = 3000;
    let rtp_time = MediaTime::new(
        pc.video_frame_count * ticks_per_frame,
        NonZeroU32::new(90_000).unwrap().into(),
    );

    writer
        .write(pt, Instant::now(), rtp_time, vp8_data)
        .map_err(|e| format!("Failed to write video: {e}"))?;

    pc.video_frame_count += 1;
    Ok(())
}

/// Run one iteration of the I/O loop. Returns events and next deadline.
pub fn poll_once(
    pc: &mut PeerConnectionInner,
    socket: &UdpSocket,
    _recv_buf: &mut [u8],
) -> Result<(Vec<PcEvent>, Instant), String> {
    // str0m's do_poll_output calls dtls.poll_output() which requires dimpl's
    // handle_timeout to have been called. But str0m's do_handle_timeout does NOT
    // propagate to dtls.handle_timeout — only init_dtls does (called during SDP
    // negotiation). So we must not call poll_output until SDP has been exchanged.
    if !pc.dtls_initialized {
        tracing::trace!(pc_id = %pc.id, "poll_once: DTLS not initialized, skipping");
        return Ok((Vec::new(), Instant::now() + Duration::from_millis(50)));
    }

    let mut events = Vec::new();

    loop {
        // dimpl (str0m's DTLS layer) requires handle_timeout before EVERY
        // poll_output call, not just once per cycle. Feed a timeout each iteration.
        pc.rtc
            .handle_input(Input::Timeout(Instant::now()))
            .map_err(|e| format!("timeout error: {e}"))?;

        match pc.rtc.poll_output() {
            Ok(Output::Transmit(transmit)) => {
                pc.transmit_log_count += 1;
                let pkt_type = classify_packet(&transmit.contents);
                if pc.transmit_log_count <= 20 || pc.transmit_log_count % 100 == 0 || pkt_type != "STUN" {
                    tracing::info!(
                        pc_id = %pc.id,
                        dest = %transmit.destination,
                        len = transmit.contents.len(),
                        count = pc.transmit_log_count,
                        pkt_type,
                        "Transmit → sending UDP"
                    );
                }
                match socket.send_to(&transmit.contents, transmit.destination) {
                    Ok(n) => {
                        if pc.transmit_log_count <= 10 {
                            tracing::info!(pc_id = %pc.id, bytes = n, "UDP sent");
                        }
                    }
                    Err(e) => tracing::warn!(pc_id = %pc.id, err = %e, "UDP send failed"),
                }
            }
            Ok(Output::Event(event)) => {
                tracing::info!(pc_id = %pc.id, ?event, "str0m event");
                if let Some(pc_event) = handle_str0m_event(pc, event) {
                    events.push(pc_event);
                }
            }
            Ok(Output::Timeout(deadline)) => {
                return Ok((events, deadline));
            }
            Err(e) => {
                pc.alive = false;
                return Err(format!("str0m error: {e}"));
            }
        }
    }
}

/// Try to receive a UDP packet and feed it to str0m.
pub fn recv_and_feed(
    pc: &mut PeerConnectionInner,
    socket: &UdpSocket,
    recv_buf: &mut [u8],
    timeout: Duration,
) -> Result<(), String> {
    socket
        .set_read_timeout(Some(timeout.max(Duration::from_millis(1))))
        .map_err(|e| e.to_string())?;

    match socket.recv_from(recv_buf) {
        Ok((len, source)) => {
            pc.recv_log_count += 1;
            let pkt_type = classify_packet(&recv_buf[..len]);
            if pc.recv_log_count <= 20 || pc.recv_log_count % 100 == 0 || pkt_type != "STUN" {
                tracing::info!(pc_id = %pc.id, %source, len, count = pc.recv_log_count, pkt_type, "UDP received");
            }
            // Resolve 0.0.0.0 → actual interface IP so str0m can match
            // the destination to our registered ICE candidate and generate
            // STUN Binding Responses.
            let mut dest = socket.local_addr().map_err(|e| e.to_string())?;
            if dest.ip().is_unspecified() {
                if let Some(real_ip) = get_local_ip() {
                    dest.set_ip(real_ip);
                }
            }

            let input = Input::Receive(
                Instant::now(),
                Receive {
                    proto: Protocol::Udp,
                    source,
                    destination: dest,
                    contents: recv_buf[..len]
                        .try_into()
                        .map_err(|e| format!("{e:?}"))?,
                },
            );
            pc.rtc
                .handle_input(input)
                .map_err(|e| format!("handle_input error: {e}"))?;
        }
        Err(e)
            if e.kind() == std::io::ErrorKind::WouldBlock
                || e.kind() == std::io::ErrorKind::TimedOut =>
        {
            pc.rtc
                .handle_input(Input::Timeout(Instant::now()))
                .map_err(|e| format!("timeout error: {e}"))?;
        }
        Err(e) => {
            return Err(format!("recv error: {e}"));
        }
    }
    Ok(())
}

/// Classify a UDP packet by its first byte (RFC 7983 demultiplexing).
fn classify_packet(data: &[u8]) -> &'static str {
    match data.first() {
        Some(0..=3) => "STUN",       // STUN Binding Request/Response/Indication
        Some(20..=63) => "DTLS",      // DTLS records (ContentType: 20=ChangeCipherSpec, 21=Alert, 22=Handshake, 23=ApplicationData)
        Some(128..=191) => "RTP/RTCP", // RTP (128-191) or RTCP
        Some(b) => {
            if *b == 0 || *b == 1 {
                "STUN"
            } else {
                "UNKNOWN"
            }
        }
        None => "EMPTY",
    }
}

fn handle_str0m_event(pc: &mut PeerConnectionInner, event: Event) -> Option<PcEvent> {
    match event {
        Event::IceConnectionStateChange(state) => {
            tracing::info!(pc_id = %pc.id, ?state, "ICE state changed");
            let mapped = match state {
                IceConnectionState::New => IceState::New,
                IceConnectionState::Checking => IceState::Checking,
                IceConnectionState::Connected => IceState::Connected,
                IceConnectionState::Completed => IceState::Completed,
                IceConnectionState::Disconnected => {
                    pc.alive = false;
                    IceState::Disconnected
                }
            };
            Some(PcEvent::IceConnectionStateChange(mapped))
        }
        Event::Connected => {
            tracing::info!(pc_id = %pc.id, "Peer connected (DTLS+ICE)");
            Some(PcEvent::Connected)
        }
        Event::MediaAdded(media) => {
            tracing::info!(pc_id = %pc.id, ?media, "Media added");
            pc.remote_mids.insert(media.mid, media.kind);
            match media.kind {
                MediaKind::Audio if pc.audio_mid.is_none() => {
                    pc.audio_mid = Some(media.mid);
                }
                MediaKind::Video if pc.video_mid.is_none() => {
                    pc.video_mid = Some(media.mid);
                }
                _ => {}
            }
            Some(PcEvent::RemoteTrackAdded {
                mid: media.mid.to_string(),
                kind: match media.kind {
                    MediaKind::Audio => "audio".to_string(),
                    MediaKind::Video => "video".to_string(),
                },
            })
        }
        Event::MediaData(data) => {
            if data.params.spec().codec == Codec::Opus {
                Some(PcEvent::AudioData(data.data.to_vec()))
            } else if data.params.spec().codec == Codec::Vp8 {
                Some(PcEvent::VideoData(data.data.to_vec()))
            } else {
                None
            }
        }
        _ => {
            tracing::info!(pc_id = %pc.id, ?event, "Unhandled str0m event");
            None
        }
    }
}
